version: '3'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: web
      volumes:
        - ./:/var/www/html/
      ports:
        - 8080:80
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql/
    ports:
      - 3306:3306
